staging-settings:
  user-workflow:
    workflow-name: regledger-readonly-staging
    deployment-registry: private
  workflow-artifacts:
    workflow-path: ./main.ts
    config-path: ./config.staging.json
    secrets-path: ""
